spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/experiment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 'now()'
      logic-not-delete-value: 'null'

logging:
  level:
    org.fn.persistence: debug