server:
  port: 8080

spring:
  messages:
    basename: i18n/messages
  flyway:
    enabled: false
  application:
    name: web
  config:
    import:
      - classpath:application-datasource.yml
      - classpath:application-redis.yml
  jackson:
    date-format: 'yyyy-MM-dd HH:mm:ss'
    time-zone: 'GMT+8'
    use-jackson2-defaults: false
notify:
  bot:
    type: wechat
    wechat:
      bots:
        aaa: https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key=8d187f3d-aea5-422b-8789-37029328ceb2
logging:
  config: classpath:log4j2-spring.xml